### PR TITLE
Create LICENSE.md

### PR DESCRIPTION
**Pull request by alyaahm**
I added the license in our repository.

### CODE REVIEW

**Comment by alyaahm** [comment]
I created a new pull request.

**Comment by alyaahm** [comment]
I added new file.

**Comment by kdpcapstone** [comment]
Alya will you please reply in Slack?  We need to have one place where we're
tracking everyone's responses.

**Comment by kdpcapstone** [comment]
The only reason I emailed you is because it doesn't look like Damion and
Alya are using Slack.  We really need to stay organized and put all our
responses in one place. Slack is a good application to have team
communication and a good tool to know.  If everyone wants to use another
tool, let me know, but let's use one communication source please.  It's too
time consuming to have to slack, and also send email from
various channels.  Thanks everyone.

**Pull request merged**
